#!/bin/bash

# Quét các file staged
echo "Running Gitleaks scan on staged files..."
gitleaks detect --source . --staged --no-git

if [ $? -ne 0 ]; then
    echo "Gitleaks detected secrets. Commit aborted."
    exit 1
fi

exit 0
