package com.capstone.construction.infrastructure.config;

public final class Constant {
  public static final String EMAIL_PATTERN = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
  public static final String PASSWORD_PATTERN = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$";
  public static final String PHONE_PATTERN = "^[0-9]{10}$";

  // for dto and entity layer
  public static final String PT_01 = "Email must follow the format <name>@<domain>";
  public static final String PT_02 = "Invalid password. Password must contain at least one number, one uppercase letter, one lowercase letter, one special character, and be at least 8 characters long";
  public static final String PT_03 = "Email must not be null or empty";
  public static final String PT_04 = "Password must not be null or empty";
  public static final String PT_05 = "Username must not be null or empty";
  public static final String PT_06 = "Role cannot be null or empty";
  public static final String PT_07 = "Role name cannot be null or empty";
  public static final String PT_08 = "Role must have at least one user";
  public static final String PT_09 = "Profile must have one user";
  public static final String PT_10 = "Fullname cannot be null or empty";
  public static final String PT_11 = "Avatar cannot be null or empty";
  public static final String PT_12 = "Address cannot be null or empty";
  public static final String PT_13 = "Fullname cannot have digits and special characters";
  public static final String PT_14 = "Phone number must be numberic and 10 digits long";
  public static final String PT_15 = "Phone number cannot be null or empty";
  public static final String PT_16 = "Gender cannot be null or empty";
  public static final String PT_17 = "Birthdate cannot be null or empty";
  public static final String PT_18 = "Branch id cannot be null or empty";
  public static final String PT_19 = "Department id cannot be null or empty";
  public static final String PT_20 = "Employee code cannot be null or empty";

  public static final String PT_21 = "Commune name cannot be null or empty";
  public static final String PT_22 = "Commune type cannot be null or empty";
  public static final String PT_23 = "Network name cannot be null or empty";
  public static final String PT_24 = "Hamlet name cannot be null or empty";
  public static final String PT_25 = "Hamlet type cannot be null or empty";
  public static final String PT_26 = "Commune cannot be null";
  public static final String PT_27 = "Customer name cannot be null or empty";
  public static final String PT_28 = "Contract fee cannot be null";
  public static final String PT_29 = "Survey fee cannot be null";
  public static final String PT_30 = "Survey effort cannot be null";
  public static final String PT_31 = "Installation fee cannot be null";
  public static final String PT_32 = "Labor coefficient cannot be null";
  public static final String PT_33 = "General cost coefficient cannot be null";
  public static final String PT_34 = "Precalculated tax coefficient cannot be null";
  public static final String PT_35 = "Construction machinery coefficient cannot be null";
  public static final String PT_36 = "Vat coefficient cannot be null";
  public static final String PT_37 = "Design coefficient cannot be null";
  public static final String PT_38 = "Design fee cannot be null";
  public static final String PT_39 = "Water meter type cannot be null or empty";
  public static final String PT_40 = "Water meter code cannot be null or empty";
  public static final String PT_41 = "Design image url cannot be null or empty";
  public static final String PT_42 = "Create by cannot be null or empty";
  public static final String PT_43 = "Water meter id cannot be null or empty";
  public static final String PT_44 = "Form number cannot be null or empty";
  public static final String PT_45 = "Representative cannot be null or empty";
  public static final String PT_46 = "Business position cannot be null or empty";
  public static final String PT_47 = "House number cannot be null or empty";
  public static final String PT_48 = "Citizen identification number cannot be null or empty";
  public static final String PT_49 = "Citizen identification provide date cannot be null or empty";
  public static final String PT_50 = "Citizen identification provide location cannot be null or empty";
  public static final String PT_51 = "Tax code cannot be null or empty";
  public static final String PT_52 = "Bank account number cannot be null or empty";
  public static final String PT_53 = "Bank account provider location cannot be null or empty";
  public static final String PT_54 = "Usage target cannot be null or empty";
  public static final String PT_55 = "Received form at cannot be null";
  public static final String PT_56 = "Number of household cannot be null";
  public static final String PT_57 = "Household registration number cannot be null";
  public static final String PT_58 = "Road cannot be null";
  public static final String PT_59 = "Network cannot be null";
  public static final String PT_60 = "Unit cannot be null";
  public static final String PT_61 = "Hamlet cannot be null";
  public static final String PT_62 = "Overall water meter ID cannot be null or empty";
  public static final String PT_63 = "Contract ID cannot be null or empty";
  public static final String PT_64 = "Registration date cannot be null";
  public static final String PT_65 = "Employee in charge ID cannot be null or empty";
  public static final String PT_66 = "Installation form cannot be null";
  public static final String PT_67 = "Receipt number cannot be null or empty";
  public static final String PT_68 = "Payment date cannot be null";
  public static final String PT_69 = "Is paid cannot be null";
  public static final String PT_70 = "Lateral name cannot be null or empty";
  public static final String PT_71 = "Neighborhood unit name cannot be null or empty";
  public static final String PT_72 = "Road name cannot be null or empty";
  public static final String PT_73 = "Roadmap name cannot be null or empty";
  public static final String PT_74 = "Lateral cannot be null";
  public static final String PT_75 = "Job content cannot be null or empty";
  public static final String PT_76 = "Connection fee cannot be null";
  public static final String PT_77 = "Note cannot be null or empty";
  public static final String PT_78 = "Schedule survey at cannot be null";

  // for service layer
  public static final String SE_01 = "Email has been existing";
  public static final String SE_02 = "Email not found";
}
