-- drop database if exists microservice;
--
-- create database microservice;

CREATE EXTENSION IF NOT EXISTS unaccent;

-- Auth
drop table if exists public.individual_notification cascade;
create table public.individual_notification
(
  notification_id varchar(255)          not null,
  user_id         varchar(255)          not null,
  is_read         boolean default false not null,
  primary key (notification_id, user_id)
);

drop table if exists public.temp cascade;
create table public.temp
(
  id      integer generated by default as identity
    primary key,
  content varchar(255)
);

drop table if exists public.user_devices cascade;
create table public.user_devices
(
  id            bigint generated by default as identity
    primary key,
  device_id     varchar(255) not null,
  device_info   varchar(255),
  ip_address    varchar(255),
  is_known      boolean      not null,
  last_login_at timestamp(6) not null,
  user_id       varchar(255) not null
);

drop table if exists public.user_roles cascade;
create table public.user_roles
(
  role_id varchar(255) not null
    primary key,
  name    varchar(255) not null
    constraint uk182xa1gitcxqhaq6nn3n2kmo3
      unique
    constraint user_roles_name_check
      check ((name)::text = ANY
             ((ARRAY ['IT_STAFF'::character varying, 'PLANNING_TECHNICAL_DEPARTMENT_HEAD'::character varying, 'SURVEY_STAFF'::character varying, 'ORDER_RECEIVING_STAFF'::character varying, 'FINANCE_DEPARTMENT'::character varying, 'CONSTRUCTION_DEPARTMENT_HEAD'::character varying, 'CONSTRUCTION_DEPARTMENT_STAFF'::character varying, 'BUSINESS_DEPARTMENT_HEAD'::character varying, 'METER_INSPECTION_STAFF'::character varying, 'COMPANY_LEADERSHIP'::character varying])::text[]))
);

drop table if exists public.users cascade;
create table public.users
(
  user_id                 varchar(255) not null
    primary key,
  created_at              timestamp(6) not null,
  department_id           varchar(255) not null,
  electronic_signing_url  varchar(255),
  email                   varchar(255) not null
    constraint uk6dotkott2kjsp8vw4d0m25fb7
      unique,
  is_enabled              boolean      not null,
  is_locked               boolean      not null,
  locked_at               timestamp(6),
  locked_reason           varchar(255),
  updated_at              timestamp(6) not null,
  username                varchar(255) not null
    constraint ukr43af9ap4edm43mmtq01oddj6
      unique,
  water_supply_network_id varchar(255) not null,
  role_id                 varchar(255)
    constraint fkh555fyoyldpyaltlb7jva35j2
      references public.user_roles
);

drop table if exists public.business_pages_of_employees cascade;
create table public.business_pages_of_employees
(
  page_id       varchar(255) not null,
  users_user_id varchar(255) not null
    constraint fkg7u0fnqxlkw834xr6tq1fcgdr
      references public.users,
  primary key (users_user_id, page_id)
);

drop table if exists public.employee_job cascade;
create table public.employee_job
(
  job_id        varchar(255) not null,
  users_user_id varchar(255) not null
    constraint fki8amwm622upo9s9bxg8l0ofjd
      references public.users,
  primary key (users_user_id, job_id)
);

drop table if exists public.profile cascade;
create table public.profile
(
  user_id      varchar(255) not null
    primary key
    constraint fks14jvsf9tqrcnly0afsv0ngwv
      references public.users,
  address      varchar(255),
  avatar_url   varchar(255),
  birthday     date,
  gender       boolean,
  phone_number varchar(255) not null
    constraint ukrc7r62u5tals0tl5rkeyyo5sb
      unique
);

drop table if exists public.verification_codes cascade;
create table public.verification_codes
(
  email               varchar(255) not null
    primary key,
  attempt_count       integer      not null,
  blocked_until       timestamp(6),
  expired_at          timestamp(6) not null,
  last_generated_time timestamp(6),
  otp_code            varchar(255) not null
);

-- construction
drop table if exists public.commune cascade;
create table public.commune
(
  commune_id  varchar(255) not null
    primary key,
  created_at  timestamp(6) not null,
  name        varchar(255) not null
    constraint ukn3jywsvnfyd63plqb3hkruu6x
      unique,
  name_search varchar(255),
  type        varchar(255) not null
    constraint commune_type_check
      check ((type)::text = ANY
             ((ARRAY ['URBAN_WARD'::character varying, 'RURAL_COMMUNE'::character varying])::text[])),
  updated_at  timestamp(6) not null
);

drop table if exists public.hamlet cascade;
create table public.hamlet
(
  hamlet_id  varchar(255) not null
    primary key,
  created_at timestamp(6) not null,
  name       varchar(255) not null
    constraint ukg4hiqr6ln2dg5ih0m61pysgxk
      unique,
  type       varchar(255) not null
    constraint hamlet_type_check
      check ((type)::text = ANY ((ARRAY ['HAMLET'::character varying, 'VILLAGE'::character varying])::text[])),
  updated_at timestamp(6) not null,
  commune_id varchar(255)
    constraint fkkogj6xatjfux0muqtijayk7l6
      references public.commune
);

drop table if exists public.neighborhood_unit cascade;
create table public.neighborhood_unit
(
  unit_id    varchar(255) not null
    primary key,
  created_at timestamp(6) not null,
  name       varchar(255) not null
    constraint uksjde4p5vuaxgd9pw5l3qcyy2t
      unique,
  updated_at timestamp(6) not null,
  commune_id varchar(255)
    constraint fk44wassxu1tvwdtm95v3xt7r4o
      references public.commune
);

drop table if exists public.road cascade;
create table public.road
(
  road_id    varchar(255) not null
    primary key,
  created_at timestamp(6) not null,
  name       varchar(255) not null
    constraint ukmucrx2d2ypmdj5b8p47at2u23
      unique,
  updated_at timestamp(6) not null
);

drop table if exists public.water_supply_network cascade;
create table public.water_supply_network
(
  branch_id  varchar(255) not null
    primary key,
  created_at timestamp(6) not null,
  name       varchar(255) not null
    constraint ukaw3rdl4uk0cqcyo9v1yu2v8de
      unique,
  updated_at timestamp(6) not null
);

drop table if exists public.installation_form cascade;
create table public.installation_form
(
  form_code                               varchar(255) not null,
  form_number                             varchar(36)  not null,
  address                                 varchar(255) not null,
  bank_account_number                     varchar(255) not null,
  bank_account_provider_location          varchar(255) not null,
  citizen_identification_number           varchar(12)  not null,
  citizen_identification_provide_date     varchar(255) not null,
  citizen_identification_provide_location varchar(255) not null,
  constructed_by                          varchar(255),
  created_at                              timestamp(6) not null,
  created_by                              varchar(255) not null,
  customer_name                           varchar(255) not null,
  customer_type                           varchar(255) not null
    constraint installation_form_customer_type_check
      check ((customer_type)::text = ANY
             ((ARRAY ['FAMILY'::character varying, 'COMPANY'::character varying])::text[])),
  handover_by                             varchar(255),
  household_registration_number           integer      not null,
  number_of_household                     integer      not null,
  overall_water_meter_id                  varchar(255) not null,
  phone_number                            varchar(10)  not null,
  received_form_at                        date         not null,
  representative                          jsonb,
  schedule_survey_at                      date,
  status                                  jsonb        not null
    constraint installation_form_status_check
      check (
        (status ->> 'contract' IN ('PROCESSING', 'PENDING_FOR_APPROVAL', 'APPROVED', 'REJECTED')) AND
        (status ->> 'estimate' IN ('PROCESSING', 'PENDING_FOR_APPROVAL', 'APPROVED', 'REJECTED')) AND
        (status ->> 'construction' IN ('PROCESSING', 'PENDING_FOR_APPROVAL', 'APPROVED', 'REJECTED')) AND
        (status ->> 'registration' IN ('PROCESSING', 'PENDING_FOR_APPROVAL', 'APPROVED', 'REJECTED'))
        ),
  tax_code                                varchar(255),
  updated_at                              timestamp(6) not null,
  usage_target                            varchar(255) not null
    constraint installation_form_usage_target_check
      check ((usage_target)::text = ANY
             ((ARRAY ['DOMESTIC'::character varying, 'INSTITUTIONAL'::character varying, 'INDUSTRIAL'::character varying, 'COMMERCIAL'::character varying])::text[])),
  water_supply_network_id                 varchar(255)
    constraint fkqyc815wmilxlmy6uksjqadjdl
      references public.water_supply_network,
  primary key (form_code, form_number)
);

drop table if exists public.construction_request cascade;
create table public.construction_request
(
  id                            varchar(255) not null
    primary key,
  contract_id                   varchar(255) not null,
  created_at                    timestamp(6) not null,
  updated_at                    timestamp(6) not null,
  installation_form_form_code   varchar(255),
  installation_form_form_number varchar(36),
  constraint uk3l14rwso7ddv5c1nrfvjs4fka
    unique (installation_form_form_code, installation_form_form_number),
  constraint fkcw1o1cf9l9e3x8w0cp5leitop
    foreign key (installation_form_form_code, installation_form_form_number) references public.installation_form
);

drop table if exists public.cost_estimate cascade;
create table public.cost_estimate
(
  estimation_id                      varchar(255) not null
    primary key,
  address                            varchar(255) not null,
  construction_machinery_coefficient integer,
  contract_fee                       integer,
  create_by                          varchar(255) not null,
  created_at                         timestamp(6) not null,
  customer_name                      varchar(255) not null,
  design_coefficient                 integer,
  design_fee                         integer,
  design_image_url                   varchar(255),
  general_cost_coefficient           integer,
  installation_fee                   integer,
  labor_coefficient                  integer,
  note                               varchar(255),
  overall_water_meter_id             varchar(255) not null,
  precalculated_tax_coefficient      integer,
  registration_at                    date         not null,
  significance                       jsonb,
  survey_effort                      integer,
  survey_fee                         integer,
  updated_at                         timestamp(6) not null,
  vat_coefficient                    integer,
  water_meter_serial                 varchar(255),
  installation_form_form_code        varchar(255),
  installation_form_form_number      varchar(36),
  constraint ukoxhdwqay1l4rf08vh8ox7iuou
    unique (installation_form_form_code, installation_form_form_number),
  constraint fkd0hrmii0s9vndliepsyjr4y1k
    foreign key (installation_form_form_code, installation_form_form_number) references public.installation_form
);

drop table if exists public.laterals cascade;
create table public.laterals
(
  lateral_id              varchar(255) not null
    primary key,
  created_at              timestamp(6) not null,
  name                    varchar(255) not null
    constraint uk8tcdg3nw5kepopyujyq1fg5ww
      unique,
  updated_at              timestamp(6) not null,
  water_supply_network_id varchar(255)
    constraint fknd58hto6lft7ym4q37l1mo882
      references public.water_supply_network
);

drop table if exists public.receipt cascade;
create table public.receipt
(
  address                       varchar(255) not null,
  attach                        varchar(255),
  created_at                    timestamp(6) not null,
  customer_name                 varchar(255) not null,
  is_paid                       boolean      not null,
  payment_date                  date         not null,
  payment_reason                varchar(255) not null,
  receipt_number                varchar(255) not null,
  significance                  jsonb,
  total_money_in_characters     varchar(255),
  total_money_in_digits         varchar(255) not null,
  updated_at                    timestamp(6) not null,
  installation_form_form_code   varchar(255) not null,
  installation_form_form_number varchar(36)  not null,
  primary key (installation_form_form_code, installation_form_form_number),
  constraint fkjwvoi10c5ywsbf652cxlsp58s
    foreign key (installation_form_form_code, installation_form_form_number) references public.installation_form
);

drop table if exists public.roadmap cascade;
create table public.roadmap
(
  roadmap_id              varchar(255) not null
    primary key,
  assigned_staff_id       varchar(255),
  created_at              timestamp(6) not null,
  name                    varchar(255) not null
    constraint uken8xqs8c9yv3lca2n3wdk93fp
      unique,
  updated_at              timestamp(6) not null,
  lateral_id              varchar(255)
    constraint fkoedg1n2o1rlegyb2bfy6ll60k
      references public.laterals,
  water_supply_network_id varchar(255)
    constraint fk39pm43hgtx23mxi4t7a6w8m25
      references public.water_supply_network
);

drop table if exists public.settlement cascade;
create table public.settlement
(
  settlement_id                 varchar(255)   not null
    primary key,
  address                       varchar(255)   not null,
  connection_fee                numeric(19, 2) not null,
  created_at                    timestamp(6)   not null,
  job_content                   varchar(255)   not null,
  note                          varchar(255)   not null,
  registration_at               date           not null,
  significance                  jsonb,
  updated_at                    timestamp(6)   not null,
  installation_form_form_code   varchar(255),
  installation_form_form_number varchar(36),
  constraint uka16ybuafkf2crgemm1nivc0hs
    unique (installation_form_form_code, installation_form_form_number),
  constraint fk7glq90muysfwma3d7swfrx0gh
    foreign key (installation_form_form_code, installation_form_form_number) references public.installation_form
);

-- customer
drop table if exists public.customer cascade;
create table public.customer
(
  customer_id                       varchar(255) not null
    primary key,
  address                           varchar(255) not null,
  bank_account_name                 varchar(255) not null,
  bank_account_number               varchar(255) not null,
  bank_account_provider_location    varchar(255) not null,
  budget_relationship_code          varchar(255),
  cancel_reason                     varchar(255),
  citizen_identification_number     varchar(255) not null,
  citizen_identification_provide_at varchar(255) not null,
  connection_point                  varchar(255),
  created_at                        timestamp(6) not null,
  deduction_period                  varchar(255),
  email                             varchar(255) not null,
  fix_rate                          varchar(255),
  form_code                         varchar(255) not null
    constraint ukmcy3y2nfbclxl4b7u6gu6f1j
      unique,
  form_number                       varchar(255) not null,
  household_registration_number     integer      not null,
  installation_fee                  integer,
  is_active                         boolean      not null,
  is_big_customer                   boolean      not null,
  is_free                           boolean,
  is_sale                           boolean,
  m3sale                            varchar(255),
  monthly_rent                      integer,
  name                              varchar(255) not null,
  number_of_households              integer      not null,
  passport_code                     varchar(255),
  payment_method                    varchar(255) not null,
  phone_number                      varchar(255) not null,
  protect_environment_fee           integer      not null,
  roadmap_id                        varchar(255) not null,
  type                              varchar(255) not null
    constraint customer_type_check
      check ((type)::text = ANY ((ARRAY ['FAMILY'::character varying, 'COMPANY'::character varying])::text[])),
  updated_at                        timestamp(6) not null,
  usage_target                      varchar(255) not null
    constraint customer_usage_target_check
      check ((usage_target)::text = ANY
             ((ARRAY ['DOMESTIC'::character varying, 'INSTITUTIONAL'::character varying, 'INDUSTRIAL'::character varying, 'COMMERCIAL'::character varying])::text[])),
  water_meter_id                    varchar(255) not null,
  water_meter_type                  varchar(255) not null,
  water_price_id                    varchar(255) not null,
  contract_contract_id              varchar(255)
    constraint uk7jogikiuj4g970rd9cmqw40ix
      unique
);

drop table if exists public.bill cascade;
create table public.bill
(
  amount_need_to_pay   varchar(255),
  bill_name            varchar(255) not null,
  export_address       varchar(255) not null,
  note                 varchar(255),
  pay_date             date,
  total_amount         varchar(255),
  customer_customer_id varchar(255) not null
    primary key
    constraint fkgyrd47ch48jc8rkya5r5e5t9y
      references public.customer
);

drop table if exists public.water_usage_contract cascade;
create table public.water_usage_contract
(
  contract_id    varchar(255) not null
    primary key,
  appendix       jsonb,
  created_at     timestamp(6) not null,
  form_code      varchar(255) not null
    constraint uksw7dgrq62u722rxtmt7aurx6i
      unique,
  form_number    varchar(255) not null,
  representative jsonb,
  updated_at     timestamp(6) not null
);

alter table public.customer
  add constraint fkephc09kiw1hcg1loxnnhnwh3q
    foreign key (contract_contract_id) references public.water_usage_contract;

-- device
drop table if exists public.materials_group cascade;
create table public.materials_group
(
  group_id   varchar(255) not null
    primary key,
  created_at timestamp(6) not null,
  name       varchar(255) not null
    constraint ukp5q73e1ej9oy70w2tvbl2502u
      unique,
  updated_at timestamp(6) not null
);

drop table if exists public.overall_water_meter cascade;
create table public.overall_water_meter
(
  serial     varchar(255) not null
    primary key,
  lateral_id varchar(255) not null,
  name       varchar(255) not null
    constraint ukb3dd1t3sdcwe8sbqfrf9dfyif
      unique
);

drop table if exists public.parameters cascade;
create table public.parameters
(
  param_id   varchar(255)   not null
    primary key,
  created_at timestamp(6)   not null,
  creator    varchar(255)   not null,
  name       varchar(255)   not null
    constraint uk103wr298mpbr2vhx5tr7ila1o
      unique,
  updated_at timestamp(6)   not null,
  updator    varchar(255)   not null,
  value      numeric(38, 2) not null
);

drop table if exists public.price_type cascade;
create table public.price_type
(
  price_type_id varchar(255) not null
    primary key,
  area          varchar(255),
  price         jsonb
);

drop table if exists public.unit cascade;
create table public.unit
(
  unit_id    varchar(255) not null
    primary key,
  created_at timestamp(6) not null,
  name       varchar(255) not null
    constraint ukaa58c9de9eu0v585le47w25my
      unique,
  updated_at timestamp(6) not null
);

drop table if exists public.material cascade;
create table public.material
(
  material_id                                   varchar(255)   not null
    primary key,
  construction_machinery_price                  numeric(19, 2) not null,
  construction_machinery_price_at_rural_commune numeric(19, 2) not null,
  created_at                                    timestamp(6)   not null,
  job_content                                   text           not null,
  labor_code                                    text           not null,
  labor_price                                   numeric(19, 2) not null,
  labor_price_at_rural_commune                  numeric(19, 2) not null,
  price                                         numeric(19, 2) not null,
  updated_at                                    timestamp(6)   not null,
  supplies_group_id                             varchar(255)
    constraint fki493ecucvdjagvmlbalqgaeb0
      references public.materials_group,
  calculation_unit_id                           varchar(255)
    constraint fkbvkkik21h23aisjcbbpgafst6
      references public.unit
);

drop table if exists public.materials_of_cost_estimate cascade;
create table public.materials_of_cost_estimate
(
  cost_est_id           varchar(255)             not null,
  mass                  real                     not null,
  note                  varchar(255),
  reduction_coefficient numeric(38, 2) default 0 not null,
  total_labor_cost      varchar(255),
  total_material_cost   varchar(255),
  material_material_id  varchar(255)             not null
    constraint fk8hlrkyr0pdjjk5yooog6ewvin
      references public.material,
  primary key (cost_est_id, material_material_id)
);

drop table if exists public.materials_of_settlement cascade;
create table public.materials_of_settlement
(
  settlement_id        varchar(255) not null,
  labor_cost           varchar(255) not null,
  material_cost        varchar(255) not null,
  note                 varchar(255),
  material_material_id varchar(255) not null
    constraint fkaueyvhmdiruotg5pccb1bpaou
      references public.material,
  primary key (material_material_id, settlement_id)
);

drop table if exists public.water_meter_type cascade;
create table public.water_meter_type
(
  type_id     varchar(255) not null
    primary key,
  created_at  timestamp(6) not null,
  diameter    real,
  max_index   varchar(255),
  meter_model varchar(255) not null,
  name        varchar(255) not null,
  origin      varchar(255) not null,
  qmin        varchar(255),
  qn          varchar(255),
  qt          varchar(255),
  size        integer,
  updated_at  timestamp(6) not null
);

drop table if exists public.water_meter cascade;
create table public.water_meter
(
  meter_code          varchar(255) not null
    primary key,
  installation_date   date         not null,
  size                integer      not null,
  water_meter_type_id varchar(255)
    constraint fk918g3f2rs9p2b4uujx5h01kiq
      references public.water_meter_type
);

drop table if exists public.usage_history cascade;
create table public.usage_history
(
  customer_id varchar(255) not null
    constraint uk7bgg9a3lubti663eagw8kamso
      unique,
  usages      jsonb,
  meter_code  varchar(255) not null
    primary key
    constraint fkrxiqn18008bmpbc73g3acvm3o
      references public.water_meter
);

drop table if exists public.water_price cascade;
create table public.water_price
(
  price_id           varchar(255)   not null
    primary key,
  application_period date           not null,
  created_at         timestamp(6)   not null,
  description        varchar(255)   not null
    constraint uk96vl1pb7ei7mnv3c2n0d1ym20
      unique,
  environment_price  numeric(38, 2),
  expiration_date    date           not null,
  tax                numeric(38, 2) not null,
  updated_at         timestamp(6)   not null,
  usage_target       varchar(255)   not null
    constraint water_price_usage_target_check
      check ((usage_target)::text = ANY
             ((ARRAY ['DOMESTIC'::character varying, 'INSTITUTIONAL'::character varying, 'INDUSTRIAL'::character varying, 'COMMERCIAL'::character varying])::text[]))
);

drop table if exists public.water_price_price_types cascade;
create table public.water_price_price_types
(
  water_price_price_id      varchar(255) not null
    constraint fkhgabkm67kgm264uwq6shrfw7r
      references public.water_price,
  price_types_price_type_id varchar(255) not null
    constraint fkdb51bbihy0304wg8eg4omfu1i
      references public.price_type
);

-- organization
drop table if exists public.business_page cascade;
create table public.business_page
(
  page_id  varchar(255) not null
    primary key,
  activate boolean      not null,
  creator  varchar(255) not null,
  name     varchar(255) not null
    constraint ukd95s8n40xd5gu8nf7k5beq3l0
      unique,
  updator  varchar(255) not null
);

drop table if exists public.department cascade;
create table public.department
(
  department_id varchar(255) not null
    primary key,
  name          varchar(255) not null
    constraint uk1t68827l97cwyxo9r1u6t4p7d
      unique,
  phone_number  varchar(255)
    constraint uk3xtr67uls6rn1u4qy6iy68ffo
      unique
);

drop table if exists public.job cascade;
create table public.job
(
  job_id     varchar(255) not null
    primary key,
  created_at timestamp(6) not null,
  name       varchar(255) not null
    constraint ukatcl7ldp04r846fq0cep4e3wi
      unique,
  updated_at timestamp(6) not null
);
