spring:
  application:
    name: notification
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
      base-path: /actuator
server:
  port: 9007
  servlet:
    context-path: /api/v1
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
keyword:
  update: update
  delete: delete
  exchange: exchange
  key: routing_key
  queue: queue
rabbit-mq-config:
  entities:
    - lateral #
    - commune #
    - unit #
    - road #
    - hamlet #
    - material_price #
    - meter_type #
    - materials_group #
    - calc_unit #
    - params #
    - water_price #
    - department #
    - employee #
# spring:
# mongodb:
# uri: mongodb://guest:guest@mongodb:27017/microservice_db?authSource=admin
#  rabbitmq:
#    host: localhost # cua may local
#    port: 5672
#    username: guest
#    password: guest
