spring:
  application:
    name: notification
  profiles:
    active: dev
  rabbitmq:
    listener:
      simple:
        missing-queues-fatal: false
        auto-startup: true
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 999999
          max-interval: 5000
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
      base-path: /actuator
server:
  port: 9007
  servlet:
    context-path: /api/v1
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
rabbit-mq-config:
  update: update
  delete: delete
  exchange: exchange
  queue: construction_queue
  entities:
    - lateral
    - commune
    - neighborhood-unit
    - road
    - hamlet
    - material-price
    - meter_type
    - materials-group
    - calculation-unit
    - params
    - water-price
    - department
    - employee
  actions:
    - update
    - delete
# spring:
# mongodb:
# uri: mongodb://guest:guest@mongodb:27017/microservice_db?authSource=admin
#  rabbitmq:
#    host: localhost # cua may local
#    port: 5672
#    username: guest
#    password: guest
