@keycloak=http://localhost:8080/realms/cmsn/protocol/openid-connect
@client_secret=

### username is username
POST {{keycloak}}/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=password&
client_id=&
client_secret={{client_secret}}&
username=&
password=&
scope=openid

> {%
  client.global.set("access_token", response.body.access_token);
  client.global.set("refresh_token", response.body.refresh_token);
%}

###
@uri = http://localhost:9008

# Happy case
### Get the first page
GET {{uri}}/api/v1/business-pages?page=0&size=10
Authorization: Bearer {{access_token}}

### Get the second page without providing page size
GET {{uri}}/api/v1/business-pages?page=1

### Get the third page
GET {{uri}}/api/v1/business-pages?page=2

### Get the first page with larger page size
GET {{uri}}/api/v1/business-pages?page=0&size=20

### Missing page index and page size
GET {{uri}}/api/v1/business-pages

# Unhappy case
### Page index is a negative number
GET {{uri}}/api/v1/business-pages?page=-1

### Page size is a negative number
GET {{uri}}/api/v1/business-pages?size=-1
