package com.capstone.auth.domain.model.enumerate;

public enum RoleName {
  IT_DEPARTMENT_STAFF,
  PLANNING_TECHNICAL_DEPARTMENT_STAFF,
  PLANNING_TECHNICAL_DEPARTMENT_HEAD,
  CONSTRUCTION_DEPARTMENT_STAFF,
  CONSTRUCTION_DEPARTMENT_HEAD,
  SALES_DEPARTMENT_STAFF,
  SALES_DEPARTMENT_HEAD,
  FINANCE_DEPARTMENT,
}
