@keycloak = http://localhost:8080/realms/cmsn/protocol/openid-connect
@client_secret =

### username is username
POST {{keycloak}}/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type = password &
client_id =  &
client_secret = {{client_secret}} &
username =  &
password =  &
scope = openid

> {%
  client.global.set("access_token", response.body.access_token);
  client.global.set("refresh_token", response.body.refresh_token);
%}

### login
POST http://14.225.198.198:8000/auth/auth/login
Content-Type: application/json

{
  "username": "survey_staff1",
  "password": "12345678"
}

### logout
POST {{keycloak}}/logout
Content-Type: application/x-www-form-urlencoded
Accept: application/json

client_id =  &
client_secret = {{client_secret}} &
refresh_token = {{refresh_token}}
