@uri = http://localhost:8080

### Register new account for customer, happy case
POST {{uri}}/auth/signup
Content-Type: application/json
Accept: application/json

{
  "username": "hoantxhe",
  "email": "@gmail.com",
  "fullName": "",
  "password": "@",
  "status": false
}

### Register new account for customer, unhappy case (wrong email format)
POST {{uri}}/auth/signup
Content-Type: application/json
Accept: application/json

{
  "username": "",
  "email": ".com",
  "fullName": "",
  "password": "@",
  "status": false
}

### Swagger UI
GET http://localhost:8000/auth/v3/api-docs

### Health check
GET http://localhost:8000/auth/health
