export const NEXT_PUBLIC_API_GATEWAY = process.env.NEXT_PUBLIC_API_GATEWAY;
export const NEXT_PUBLIC_SOCKET_URL = process.env.NEXT_PUBLIC_SOCKET_URL;
export const NEXT_PUBLIC_KEYCLOAK_URL = process.env.NEXT_PUBLIC_KEYCLOAK_URL;
export const NEXT_PUBLIC_BACKEND_API = process.env.NEXT_PUBLIC_BACKEND_API;

export const NEXT_PUBLIC_REALM = process.env.NEXT_PUBLIC_REALM;
export const NEXT_PUBLIC_CLIENT_ID = process.env.NEXT_PUBLIC_CLIENT_ID;