import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FB' },
  header: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  backText: { fontSize: 15, color: '#2563EB', fontWeight: '500' },
  headerLeft: { flexDirection: 'row', alignItems: 'center' },
  backButton: { marginRight: 4 },
  breadcrumb: { fontSize: 14, color: '#8B92A8', fontWeight: '400' },
  breadcrumbSeparator: { fontSize: 14, color: '#D1D5DB', marginHorizontal: 8 },
  breadcrumbActive: { fontSize: 14, color: '#1A1D2E', fontWeight: '600' },
  scrollView: { flex: 1 },
  card: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    marginTop: 24,
    borderRadius: 16,
    padding: 0,
    overflow: 'hidden',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1A1D2E',
    letterSpacing: -0.3,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F4FF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  editIcon: { margin: 0, padding: 0 },
  editText: {
    fontSize: 14,
    color: '#5B7FFF',
    fontWeight: '600',
    marginLeft: -4,
  },
  divider: { backgroundColor: '#F0F0F0', height: 1 },
  profileContent: { padding: 24 },
  row: { flexDirection: 'row', marginBottom: 32, gap: 24 },
  column: { flex: 1 },
  label: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9CA3AF',
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  value: { fontSize: 15, color: '#1A1D2E', lineHeight: 22, fontWeight: '500' },
  valueStrong: {
    fontSize: 16,
    color: '#1A1D2E',
    fontWeight: '700',
    letterSpacing: -0.2,
  },
  statusChip: {
    backgroundColor: '#D1FAE5',
    alignSelf: 'flex-start',
    height: 32,
    marginTop: 0,
  },
  statusText: {
    fontSize: 13,
    color: '#10B981',
    fontWeight: '600',
    marginHorizontal: 0,
  },
  actionsContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
    gap: 12,
  },
  actionButton: { borderColor: '#E0E0E0', borderRadius: 12, borderWidth: 1.5 },
  actionButtonLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#4A5568',
    paddingVertical: 6,
  },
});

export default styles;
