name: Deploy VPS
on:
  workflow_run:
    workflows: ["Backend Build"]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: 14.225.198.198
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          command_timeout: 30m
          script: |
            cd /home/hoan/be/be/apps
            git pull origin dev

            # Kiểm tra và khởi động Docker nếu chưa chạy
            if ! systemctl is-active --quiet docker; then
              echo "Docker is not running. Starting Docker..."
              systemctl start docker
              sleep 5
            fi

            # Dừng các container cũ với đúng các file cấu hình
            docker compose \
              -f docker-compose-db.yml \
              -f docker-compose-other.yml \
              -f docker-compose-services.yml \
              down --remove-orphans

            services=(
              auth
              construction
              customer
              device
              email
              eureka
              gateway
              image
              notification
              organization
            )

            for service in "${services[@]}"
            do
              docker pull ghcr.io/tranhoan-backend-dev/capstone-project/$service:latest
            done

            # Khởi động lại
            docker compose \
              -f docker-compose-db.yml \
              -f docker-compose-other.yml \
              up -d


            # start keycloak background
            pkill -f keycloak || true
            nohup /home/hoan/keycloak-26.5.1/bin/kc.sh start-dev > keycloak.log 2>&1 &

            # start backend services
            docker compose \
              -f docker-compose-services.yml \
              up -d
